### ISSUE TITLE
Create Path Traversal Challenge

### ISSUE THREAD

**Issue by colbycocking** [acasi-ctf/ctf#36]
- [x] Write challenge description
- [x] Write challenge
- [x] Write documentation in .md file

**Comment by EllisHZH** [comment]
Summary of challenge 3. It is Reverse challenge. The challenge will create 10 letter random string and reverse the string. User need to find out the original string.

**Comment by colbycocking** [comment]
I believe this is supposed to be a directory traversal attack.

**Comment by EthanIsakson** [comment]
Made very poor progress on this challenge. The environment I working in (A DVWA) is really giving me trouble when trying to allow the ability to traverse out of the defined Root Page. For now I am just using this challenge to continue getting "Greener" users up to speed on the structure of a websites file system by having this traverse up and discover the flag file. Since this challenge linearly follows @EllisHZH's cipher challenge I have gone ahead and applied a simply shift to the flag in hopes the user will recall the previous challenge and decrypt it. Will need to continue working to create an exploit that allows me to navigate down into www or var files.

**Comment by EthanIsakson** [comment]
Update: Been reading up on Apache config and was able to make modifications to the "Root Webpage" so I was able to get in etc/ directory. Now just need to do some patch work so that the webpage is configured for a new working dir.

**Comment by EthanIsakson** [comment]
Still need to walk back through the container and solidify file permissions and rework the security. Once I have that I will finishing writing up the documentation or guide.

**Comment by DungLe2911** [comment]
I think we are good to close this issues now. All the requirements are met

**Comment by EthanIsakson** [comment]
Update on this. I was writing the directory traversal attack and was having extremely difficulty getting everything you needed to know within the guide. I decided to rework this slot to serve as a path traversal tutorial. This will serve as part one for my directory traversal attack challenge which I will push to summer session

**Comment by EthanIsakson** [comment]
Path traversal challenge is complete to my liking.
